WebApplication19/Models/About.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace WebApplication19.Models
{
    public class About
    {
        [Key]
        public int Id { get; set; }
        
        public  string? PhoneNumber { get; set; }
        
        public string? Birthday { get; set; }
        public string? Website { get; set; }
        public string? Age { get; set; }
        public string? City { get; set; }
        public string? Email { get; set; }
        public byte[]? ProfileImg { get; set; }
        public byte[]? HeroImg { get; set; }
    }
}

WebApplication19/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication19.Models
{
    public class Contact
    {
        [Key]
        public int Id { get; set; }
        
        public string? MyEmail { get; set; }
        public string? Call { get; set; }
        public string? Location { get; set; }
    }
}

WebApplication19/Models/ContactMessage.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication19.Models
{
    public class ContactMessage
    {
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? Subject { get; set; }
        public string? Message { get; set; }

    }
}

WebApplication19/Models/Example.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication19.Models
{
    public class Example
    {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Subject { get; set; }
        public string? Website { get; set; }
        public string? NumberOfPage { get; set; }
        public byte[]? ExampleImg1 { get; set; }
        public byte[]? ExampleImg2 { get; set; }

        public byte[]? ExampleImg3 { get; set; }


    }
}

WebApplication19/Models/Skill.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication19.Models
{
    public class Skill
    {
        [Key]
        public int Id { get; set; }
        public string? SkillName { get; set; }
        public string? SkillIcon { get; set;}
    }
}

WebApplication19/ViewModels/About_ViewModels.cs
using Microsoft.VisualBasic;

namespace WebApplication19.ViewModels
{
    public class About_ViewModels
    {
        public string PhoneNumber { get; set; }
        public string Birthday { get; set; }
        public string Website { get; set; }
        public string Age { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public IFormFile ProfileImg { get; set; }
        public IFormFile HeroImg { get; set; }
    }
}

WebApplication19/ViewModels/ContactMessage_ViewModels.cs
namespace WebApplication19.ViewModels
{
    public class ContactMessage_ViewModels
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        

    }
}

WebApplication19/ViewModels/Contact_ViewModels.cs
namespace WebApplication19.ViewModels
{
    public class Contact_ViewModels
    {
        
        public string MyEmail { get; set; }
        public string Call { get; set; }
        public string Location { get; set; }

    }
}

WebApplication19/ViewModels/Example_ViewModels.cs
namespace WebApplication19.ViewModels
{
    public class Example_ViewModels
    {
        public string Title { get; set; }

        public string Subject { get; set; }
        public string Website { get; set; }
        public string NumberOfPage { get; set; }
        public IFormFile ExampleImg1 { get; set; }
        public IFormFile ExampleImg2 { get; set; }

        public IFormFile ExampleImg3 { get; set; }
    }
}

WebApplication19/ViewModels/Skill_ViewModels.cs
namespace WebApplication19.ViewModels
{
    public class Skill_ViewModels
    {
        public string SkillName { get; set; }
        public string SkillIcon { get; set; }
    }
}

WebApplication19/Controllers/ManagerController.cs
using AutoMapper;
using WebApplication19.Models;
using WebApplication19.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication19.Controllers
{
    public class ManagerController : Controller
    {
        public IActionResult Index_Home()
        {
            MyWebsiteFirstCode db = new MyWebsiteFirstCode();

            List<About> abt = db.Abouts.ToList();
            ViewData["AboutList"] = abt;

            List<Skill> skl = db.Skills.ToList();
            ViewData["SkillList"] = skl;

            List<Example> exm = db.Examples.ToList();
            ViewData["ExampleList"] = exm;

            List<Contact> cnt = db.Contacts.ToList();
            ViewData["ContactList"] = cnt;
            return View();
        }

        public IActionResult About()
        {
            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            List<About> abt = db.Abouts.ToList();
            ViewData["AboutList"] = abt;
           return View();
        }
        public IActionResult Skill() 
        {
            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            List<Skill> skl = db.Skills.ToList();
            ViewData["SkillList"] = skl;
            return View();
        }
        public IActionResult Contact()
        {
            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            List<Contact> cnt = db.Contacts.ToList();
            ViewData["ContactList"] = cnt;
            return View();
        }
        public IActionResult Example()
        {
            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            List<Example> exm = db.Examples.ToList();
            ViewData["ExampleList"] = exm;
            return View();
        }
        public IActionResult ContactMessage()
        {
            return View();
        }

        public IActionResult Add_Skill(Skill_ViewModels skill, [FromServices] IMapper mapper)
        {
             MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            Skill skl = mapper.Map<Skill>(skill);     
            db.Add(skl);
            db.SaveChanges();
            return RedirectToAction("Skill");
        }
        public IActionResult Add_Example(Example_ViewModels example, [FromServices] IMapper mapper)
        {
            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            Example exl = mapper.Map<Example>(example);
            db.Add(exl);
            db.SaveChanges();
            return RedirectToAction("Example");
        }
        public IActionResult Delete_Skill(List<int> DeleteSkillIds)
        {
            
                MyWebsiteFirstCode db = new MyWebsiteFirstCode();
                List<Skill> skl = db.Skills.Where(x => DeleteSkillIds.Contains(x.Id) == true).ToList();
                db.RemoveRange(skl);
                db.SaveChanges();
                return RedirectToAction("Skill");
            
        }
        public IActionResult Delete_Example(List<int> DeleteExampleIds)
        {

            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            List<Example> exm = db.Examples.Where(x => DeleteExampleIds.Contains(x.Id) == true).ToList();
            db.RemoveRange(exm);
            db.SaveChanges();
            return RedirectToAction("Example");

        }

        public IActionResult Update_About(int id, string Birthday, string Phonenumber, string City, string Website, string Age, string Email)
        {

            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            About abt = db.Find<About>(id);
            abt.PhoneNumber = Phonenumber;
            abt.Birthday = Birthday;
            abt.Email = Email;
            abt.City = City;
            abt.Age = Age;
            abt.Website = Website;
            db.Update(abt);
            db.SaveChanges(true);
            return RedirectToAction ("About");

        }
        public IActionResult Update_Contact(int id,  string Call, string Location, string MyEmail)
        {
            MyWebsiteFirstCode db = new MyWebsiteFirstCode();
            Contact cnt = db.Find<Contact>(id);
            cnt.Location = Location;
            cnt.Call = Call;
            cnt.MyEmail = MyEmail;
            db.Update(cnt);
            db.SaveChanges(true);
            return RedirectToAction("Contact");

        }

    }
}

WebApplication19/Views/Manager/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout_Mng_Edit_About.cshtml";
}
@model About_ViewModels
@{
   
    foreach (var item in ViewData["AboutList"] as List<About>)
    {
<form asp-action="Update_About" asp-controller="Manager">
<div class="container" >
    <div class="section-title">
        <h2 style="font-size:80px">Edit</h2>
    </div>
    <div class="section-title">
        <h2>About</h2>
    </div>

    <div class="col-lg-6" data-aos="fade-right" style="padding:40px; border-bottom:groove">
        <img src="~/Layout/assets/img/hero-bg.jpg" class="img-fluid rounded" alt="">
        <input type="file" class="btn btn-success col-12 rounded" style="margin-top:10px" asp-for="HeroImg" >

    </div>
    <div class="row" style="padding:40px; border-bottom:groove">
        <div class="col-lg-4" data-aos="fade-right">
            <img src="~/Layout/assets/img/profile-img.jpg" class="img-fluid rounded" alt="">
            <input type="file" class="btn btn-success col-12 rounded" style="margin-top:10px" asp-for="ProfileImg">

        </div>

        <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
            <div class="row">
                <div class="col-lg-6">
                    <ul>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <input value="@item.Birthday" asp-for="Birthday" autocomplete="off"> </li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <input value="@item.Website" asp-for="Website" autocomplete="off"></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <input value="@item.PhoneNumber" asp-for="PhoneNumber" autocomplete="off"></li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <input value="@item.Age" asp-for="Age" autocomplete="off"></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Email:</strong> <input value="@item.Email" asp-for="Email" autocomplete="off"></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <input value="@item.City" asp-for="City" autocomplete="off"></li>
                    </ul>
                </div>
            </div>
            <input value="@item.Id" type="hidden" name="id"  />
            <button class="btn col-lg-6" value="@item.Id">Save Changes</button>
        </div>
    </div>

</div>
</form>
}
}

WebApplication19/Views/Manager/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout_Mng_Edit_Contact.cshtml";
}
@model Contact_ViewModels

@{
    foreach (var item in ViewData["ContactList"] as List<Contact>)
    {
        <form asp-action="Update_Contact" asp-controller="Manager">
            <div class="container" >

            <div class="section-title">
                <h2>Contact</h2>
            </div>

            <div class="row" data-aos="fade-in">

                <div class="col-lg-5 d-flex align-items-stretch">
                    <div class="info">
                        <div class="address">
                            <i class="bi bi-geo-alt"></i>
                            <h4>Location:</h4>
                            <input value="@item.Location" asp-for="Location" autocomplete="off"/>
                        </div>

                        <div class="email">
                            <i class="bi bi-envelope"></i>
                            <h4>Email:</h4>
                                <input value="@item.MyEmail" asp-for="MyEmail" autocomplete="off" />
                        </div>

                        <div class="phone">
                            <i class="bi bi-phone"></i>
                            <h4>Call:</h4>
                                <input value="@item.Call" asp-for="Call" autocomplete="off" />
                        </div>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d221880.46861860607!2d52.39026968527541!3d29.665188988194107!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3fb20d0c8c85f2e3%3A0x6d0c5b8aef6b4cf6!2sShiraz%2C%20Fars%20Province%2C%20Iran!5e0!3m2!1sen!2s!4v1673964574617!5m2!1sen!2s" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        <input value="@item.Id" type="hidden" name="id" />
                            <button class="btn col-lg-6" value="@item.Id">Save Changes</button>

                    </div>
                </div>
            </div>

        </div>
        </form>
    }
    }

WebApplication19/Views/Manager/ContactMessage.cshtml
@{
    ViewData["Title"] = "ContactMessage";
    Layout = "~/Views/Shared/_Layout_Mng_ContactMessage.cshtml";
}

WebApplication19/Views/Manager/Example.cshtml
@{
    ViewData["Title"] = "Example";
    Layout = "~/Views/Shared/_Layout_Mng_Edit_Example.cshtml";
}
@model Example_ViewModels
<div class="section-title container">
    
    <h2>Some Examples Of Our Work</h2>
    <form asp-action="Add_Example" asp-controller="Manager">
    <div class="container">
       <div class="row">
       <div class="col-6">
          <div class="row">
              <div class="col-4">
                            <label ><b>Title:</b></label><br />
                            <label style="margin-top:18px"><b>Subject:</b></label><br />
                            <label style="margin-top:18px"><b>Website:</b></label><br />
                            <label style="margin-top:15px"><b>NumberOfPage:</b></label><br />
              </div>
                        <div class="col-2">
                            <input  name="Title" asp-for="Title" autocomplete="off" autofocus /><br />
                            <input style="margin-top:10px" name="Subject" asp-for="Subject" autocomplete="off" /><br />
                            <input style="margin-top:10px" name="Website" asp-for="Website" autocomplete="off" /><br />
                            <input style="margin-top:10px" name="NumberOfPage" asp-for="NumberOfPage" autocomplete="off" /><br />

               </div>
               </div>
        </div>
                <div class="col-6" >
                    <strong style="margin-top:10px">Add Images:</strong><br />
                    <input style="margin-top:10px" type="file" name="ExampleImg1" asp-for="ExampleImg1" /><br />
                     <input style="margin-top:10px" type="file" name="ExampleImg2" asp-for="ExampleImg2" /><br />
                     <input style="margin-top:10px" type="file" name="ExampleImg3" asp-for="ExampleImg3" /><br />
                </div>
    </div>
    <div></div>
    </div>
        <div style="border-bottom:groove;padding:40px;"> <button class="btn" style="margin-top:30px;margin-left:30px">+Add Example</button>
        </div>
   
    </form>
    <form asp-action="Delete_Example" asp-controller="Manager">
    <button value="DeleteExampleIds" class="btn" style="margin-left:30px ;margin-top:100px;">-Remove Skills</button>

    @foreach (var item in ViewData["ExampleList"] as List<Example>)
    {
    <div class="col-lg-12 pt-4 pt-lg-0 content " data-aos="fade-left" style="margin-top:30px;margin-left:30px;">
                
@*        <input type="checkbox" name="DeleteExampleIds" value="@item.Id" style="margin-right:10px;" /><label><b>@item.Title</b></label>
*@                <div class="input-group mb-3">
                    <div class="input-group-text">
                        <input type="checkbox" name="DeleteExampleIds" value="@item.Id" style="margin-right:10px;" />
                    </div>
                    <input type="text" class="form-control-sm" value="@item.Title">
                </div>
        <div class="row">
            <div class="col-lg-12">
                <ul>
                    <li><i class="bi bi-chevron-right"></i> <strong>Subject:</strong> <span>@item.Subject</span></li>
                        <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>@item.Website</span></li>
                        <li><i class="bi bi-chevron-right"></i> <strong>Number Of Page:</strong> <span>@item.NumberOfPage</span></li>
                </ul>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-lg-12" data-aos="fade-right" style="border-bottom:groove">
            <div style="padding:40px;">
                   <img id="myImg" src="" alt="Northern Lights, Norway" width="auto" height="200">
                    <img id="myImg" src=""  alt="Northern Lights, Norway" width="auto" height="200">
                    <img id="myImg" src="" alt="Northern Lights, Norway" width="auto" height="200">
           </div>
        </div>
    </div>
    
    <!-- The Modal -->
    <div id="myModal" class="modal">
        <span class="close">&times;</span>
        <img class="modal-content" id="img01">
        <div id="caption"></div>
    </div>
    }
    
   </form>
</div>
   

WebApplication19/Views/Manager/Index_Home.cshtml
@{
    ViewData["Title"] = "Index_Home";
    Layout = "~/Views/Shared/_Layout_Mng_Home.cshtml";
}

<!-- ======= About Section ======= -->
@{
    foreach (var item in ViewData["AboutList"] as List<About>)
    {


        <section id="about" class="about">
            <div class="container">

                <div class="section-title">
                    <h2>About</h2>
                    <p>I am Hossein Azadpour. Ready to build up and run your desired website.</p>
                </div>

                <div class="row">
                    <div class="col-lg-4" data-aos="fade-right">
                        <img src="~/Layout/assets/img/profile-img.jpg" class="img-fluid" alt="">
                    </div>
                    <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
                        <h3>Web Developer</h3>

                        <div class="row">
                            <div class="col-lg-6">
                                <ul>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <span>@item.Birthday</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>@item.Website</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>@item.PhoneNumber</span></li>
                                </ul>
                            </div>
                            <div class="col-lg-6">
                                <ul>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>@item.Age</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Email:</strong> <span>@item.Email</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>@item.City</span></li>
                                </ul>
                            </div>
                        </div>
                        <p>
                        </p>
                    </div>
                </div>

            </div>
        </section>
    }
}<!-- End About Section -->
<!-- ======= Skills Section ======= -->
<section id="skills" class="skills section-bg">
    <div class="container">

        <div class="section-title">
            <h2>Skills</h2>
            <p></p>
        </div>

        <div class="row" style="font-size:28px;color:darkred">
            @{
                foreach (var item in ViewData["SkillList"] as List<Skill>)
                {


                    switch (item.Id)
                    {
                        case < 50:
                            <div class="col-lg-4">
                                <ul>
                                    <li><label role="none" class="@item.SkillIcon">@item.SkillName</label></li>
                                </ul>
                            </div>
                            break;
                        default:
                            break;
                    }

                }

            }

        </div>

    </div>
</section><!-- End Skills Section -->
<!-- ======= Example Section ======= -->
<section id="resume" class="resume">
    <div class="section-title container">
        <h2>Some Examples Of Our Work</h2>
        <p>Here is some Projects that developed and design by me.</p>


        @foreach (var item in ViewData["ExampleList"] as List<Example>)
        {
            <div class="col-lg-12 pt-4 pt-lg-0 content " data-aos="fade-left" style="margin-top:30px;margin-left:30px;">
                <label><b>@item.Title</b></label>
                <div class="row">
                    <div class="col-lg-12">
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <strong>Subject:</strong> <span>@item.Subject</span></li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>@item.Website</span></li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Number Of Page:</strong> <span>@item.NumberOfPage</span></li>
                        </ul>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12" data-aos="fade-right" style="border-bottom:groove">
                    <div style="padding:40px;">
                        <img id="myImg" src="" alt="Northern Lights, Norway" width="auto" height="200">
                        <img id="myImg" src="" alt="Northern Lights, Norway" width="auto" height="200">
                        <img id="myImg" src="" alt="Northern Lights, Norway" width="auto" height="200">
                    </div>
                </div>
            </div>

            <!-- The Modal -->
            <div id="myModal" class="modal">
                <span class="close">&times;</span>
                <img class="modal-content" id="img01">
                <div id="caption"></div>
            </div>
        }

    </div>


</section><!-- End Resume Section -->
<!-- ======= Services Section ======= -->
<section id="services" class="services">
    <div class="container">

        <div class="section-title">
            <h2>Services</h2>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
                <div class="icon"><i class="bi bi-pen"></i></div>
                <h4 class="title"><a>Responsive design</a></h4>
                <p class="description">Our website designing services also offer the option of responsive design. However, we recommend responsive design because it supports mobile users, which can consist of shoppers using their tablet or smartphone to browse the web.</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                <div class="icon"><i class="bi bi-database"></i></div>
                <h4 class="title"><a>Database integration</a></h4>
                <p class="description">Many company websites feature a database, such as for processing payments. We provide full support for database integration, which we separate into three tiers — basic, advanced, and full development. If your business doesn’t require a database integration, you can select, “none,” on the cost calculator.</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                <div class="icon"><i class="bi bi-briefcase"></i></div>
                <h4 class="title"><a>Content management system (CMS)</a></h4>
                <p class="description">
                    A CMS is another optional add-on for our web design services.
                    Whether you’re an ecommerce website or informational website, a CMS offers immense value. It can help your business manage and streamline your content, which can improve the efficiency of your content marketing strategy.
                </p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
                <div class="icon"><i class="bi bi-postcard"></i></div>
                <h4 class="title"><a>Customized style</a></h4>
                <p class="description">It’s essential that your website captures your brand, which is why our web design services include unlimited style options. For example, if your company requires a sophisticated design that emphasizes the quality and price range of your products, our team can achieve that for you.</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
                <div class="icon"><i class="bi bi-alexa"></i></div>
                <h4 class="title"><a>Website page creation</a></h4>
                <p class="description">
                    With our web design services, you can rely on our designers to create every page of your website.

                    Whether you’re an ecommerce store, brick-and-mortar business, or service provider, our designers can create the webpages that your company needs to reach, inform, and convert your target audience. As a full-service digital marketing agency, we also offer content marketing services to enhance your strategy.
                </p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
                <div class="icon"><i class="bi bi-search"></i></div>
                <h4 class="title"><a>Search engine optimization</a></h4>
                <p class="description">We maximize the results of your website design or redesign plan, as well as improve your digital marketing strategy, by ensuring your website follows best practices for SEO. SEO refers to an umbrella of techniques that enhance your website’s ranking for relevant search results.</p>
            </div>
        </div>

    </div>
</section><!-- End Services Section -->
<!-- ======= Contact Section ======= -->
@model ContactMessage_ViewModels
<section id="contact" class="contact">
    <div class="container">

        <div class="section-title">
            <h2>Contact</h2>

        </div>

        <div class="row" data-aos="fade-in">
            @{
                foreach (var item in ViewData["ContactList"] as List<Contact>)
                {
                    <div class="col-lg-5 d-flex align-items-stretch">
                        <div class="info">

                            <div class="address">
                                <i class="bi bi-geo-alt"></i>
                                <h4>Location:</h4>
                                <p>@item.Location</p>
                            </div>

                            <div class="email">
                                <i class="bi bi-envelope"></i>
                                <h4>Email:</h4>
                                <p>@item.MyEmail</p>
                            </div>

                            <div class="phone">
                                <i class="bi bi-phone"></i>
                                <h4>Call:</h4>
                                <p>@item.Call</p>
                            </div>

                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d221880.46861860607!2d52.39026968527541!3d29.665188988194107!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3fb20d0c8c85f2e3%3A0x6d0c5b8aef6b4cf6!2sShiraz%2C%20Fars%20Province%2C%20Iran!5e0!3m2!1sen!2s!4v1673964574617!5m2!1sen!2s" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>

                    </div>
                }
            }
            <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
                <form asp-action="SendMessage" asp-controller="Home" class="php-email-form">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Your Name</label>
                            <input asp-for="Name" id="name" class="form-control" required />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Your Email</label>
                            <input class="form-control" type="email" id="Email" asp-for="Email" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name">Subject</label>
                        <input class="form-control" id="subject" asp-for="Subject" required />
                    </div>
                    <div class="form-group">
                        <label>Message</label>
                        <textarea class="form-control" id="message" rows="10" asp-for="Message"></textarea>
                    </div>
                    <div class="my-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center"><button type="submit">Send Message</button></div>
                </form>
            </div>

        </div>

    </div>
</section>

}<!-- End Contact Section -->

WebApplication19/Views/Manager/Skill.cshtml
@{
    ViewData["Title"] = "Skill";
    Layout = "~/Views/Shared/_Layout_Mng_Edit_Skill.cshtml";
}
@model Skill_ViewModels

<div class="container">
    <form asp-action="Delete_Skill" asp-controller="Manager">
        <div class="section-title">
        <h2>Skills</h2>

    </div>
    <div class="row" style="font-size:28px;color:darkred">

        @{
            foreach (var item in ViewData["SkillList"] as List<Skill>)
            {

                
                    switch (item.Id)
                    {
                        case < 50:
                            <div class="col-lg-4">
                                <ul>
                                <li><input type="checkbox" name="DeleteSkillIds" value="@item.Id" style="margin-right:10px;" /><label role="none" class="@item.SkillIcon">@item.SkillName</label></li>
                                </ul>
                            </div>
                            break;
                        default:
                            break;
                    }

                }

            }  

     </div>
    <button value="DeleteSkillIds" class="btn" style="margin-left:30px ;margin-top:100px;">-Remove Skills</button>
    </form>
</div>
<div class="container" style="margin-top:30px;">
    <form asp-action="Add_Skill" asp-controller="Manager">
        <input placeholder="Enter Skill IconCode" name="SkillIcon" asp-for="SkillIcon" autofocus autocomplete="off"/>
        <input placeholder="Enter Skill Name" name="SkillName" asp-for="SkillName" autocomplete="off" />
<button class="btn btn-success" >+Add Skill</button>
    </form>
</div>

     